name: Gitee Pages Deploy
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build
      run: npm run build
    
    - name: Deploy to Gitee Pages
      run: |
        # 创建gh-pages分支并推送构建文件
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git checkout -b gh-pages
        git rm -rf .
        cp -r dist/* .
        echo "yangtzeu-auditoriums" > CNAME
        git add .
        git commit -m "Deploy to Gitee Pages"
        git push origin gh-pages --force